### ISSUE TITLE
Turn uint to int in Blockchain/Block

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet.net#61]
Currently, we're using `uint` / `ulong` to represent `Block.Index` and other place that contextually negative numbers are not needed.

- but In C# / .NET, these unsigned type are not compatible with common language specification(CPS) and aren't recommended for general use. ([see also](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/uint))
- and, it causes unnecessary casting to make compatible with other API(e.g. LINQ).

So, I suggest changing these unsigned type to normal type in public interfaces.

@dahlia @ipdae @kijun any ideas?

**Comment by dahlia** [comment]
If avoiding unsigned types is a norm in .NET community I am with you on this.
