### ISSUE TITLE
Loosen constraint about Block.Timestamp

### ISSUE THREAD

**Issue by longfin** [planetarium/libplanet.net#65]
Currently we require that the generated block has a timestamp higher than the timestamp of the previous block. there are a few things to consider.

- `Block.Timestamp` isn't always accurate because they are based on the local time of the system.
- Additional things (like #64 ) are required for automated testing, since the latter block requires a later timestamp.

I think we'd better loosen this constraint like Ethereum or Bitcoin style.

- In Bitcoin, a timestamp is accepted as valid if it is greater than the median timestamp of previous 11 blocks, and less than the network-adjusted time + 2 hours. ([see also](https://en.bitcoin.it/wiki/Block_timestamp))
- In Ethereum, a timestamp is accepted as valid if `block.timestamp <= now + 900` and is `block.timestamp >= parent.timestamp`. ([see also](https://github.com/ethereum/wiki/blob/c02254611f218f43cbb07517ca8e5d00fd6d6d75/Block-Protocol-2.0.md#block-validation-algorithm))

There are pros and cons, but I think the Ethereum style is more intuitive and easier to implement.

@dahlia @kijun @ipdae any ideas?

**Comment by dahlia** [comment]
If the existing code is assuming that the order of blocks are determined by its timestamp we should get rid of the assumption as well.  To me both of styles are fine.
